version: "3.7"
services:
  persons:
    image: 'persons:latest'
    build:
      context: './persons/'
    expose:
      - "8083"
    ports:
      - "8083:8083"
    networks:
      - accounts-network
  accounts:
    image: 'accounts:latest'
    build:
      context: './accounts/'
    depends_on:
      - persons
    expose:
      - "8082"
    ports:
      - "8082:8082"
    networks:
      - accounts-network
networks:
  accounts-network:
    name: accounts-network