apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  namespace: accounts-demo
  labels:
    app: accounts
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8082
  selector:
    app: accounts
---
apiVersion: v1
kind: Service
metadata:
  name: persons-service
  namespace: accounts-demo
  labels:
    app: persons
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8083
  selector:
    app: persons